### ISSUE TITLE
Flaky and Dirty Tests

### ISSUE THREAD

**Issue by stephen-ritter** [OpenC3/cosmos-playwright#3]
When running the playwright tests repeatedly the tests don't seem to clean up the OpenC3 state. It appears that cleaning up the OpenC3 volumes and then running the playwright tests fixes this, but it isn't ideal. The following are tests that seem to continuously fail after repeated runs of the playwright tests. The version of the tests I ran are from commit [83f55f855ae20cd0b7ff06c3779c065a7ba81218](https://github.com/OpenC3/cosmos-playwright/commit/83f55f855ae20cd0b7ff06c3779c065a7ba81218), and the version of OpenC3 that I am running is [v5.6.1](https://github.com/OpenC3/cosmos/tree/v5.6.1). I have attached [playwright_output.txt](https://github.com/OpenC3/cosmos-playwright/files/11467451/playwright_output.txt) which shows where it is failing.
```
Slow test file: [local] › script-runner/script-menu.spec.ts (18.5m)
Slow test file: [local] › calendar.spec.ts (9.4m)
Slow test file: [local] › admin/plugins.spec.ts (2.4m)
Slow test file: [local] › command-sender.spec.ts (1.4m)
Slow test file: [local] › script-runner/api.spec.ts (1.1m)
Consider splitting slow test files to speed up parallel execution
6 failed
  [local] › calendar.spec.ts:151:5 › #unstable (dirty test) test create timeline ─────────────────
  [local] › calendar.spec.ts:214:5 › #unstable (dirty test) test timeline select and activity delete 
  [local] › script-runner/api.spec.ts:28:5 › #unstable (dirty test) opens a target file ──────────
  [local] › script-runner/script-menu.spec.ts:147:5 › #unstable (dirty test) sets and gets stash ─
  [local] › script-runner/script-menu.spec.ts:165:5 › #unstable (dirty test) sets metadata ───────
  [local] › table-manager.spec.ts:269:5 › #unstable (dirty test) save as ─────────────────────────
2 flaky
  [local] › cmd-tlm-server/cmd-pkts.spec.ts:71:5 › #unstable (flaky test) displays a raw command ─
  [local] › cmd-tlm-server/tlm-pkts.spec.ts:48:5 › #unstable (flaky test) displays a raw packet ──
2 skipped
```

**Comment by jmthomas** [comment]
Our tests are designed to be run on a clean state in the CI/CD pipeline but I agree this isn't ideal. We'll continue to refine these as we move them to the main repo.
