### ISSUE TITLE
Tag the Playwright Test Corresponding to the Released OpenC3 Versions

### ISSUE THREAD

**Issue by stephen-ritter** [OpenC3/cosmos-playwright#4]
Would it be possible when releasing a new version of OpenC3 to tag the playwright tests with the same tag to map the two together? This makes it easier to figure out which commit of the playwright tests goes with which release of OpenC3. Right now I have to look at the date the OpenC3 release was made and find the commit that falls before that release date.

**Comment by jmthomas** [comment]
Resolved by moving playwright to the main repo
